### ISSUE TITLE
Unable to use with Mod

### ISSUE THREAD

**Issue by darkmage0707077** [iChun/Ding#1]
Hello,

I recently downloaded Ding and found it to be fantastic. While looking in the config file, I noticed that I can use it with mod sounds, too. However, upon trying to use it with audiodeath, I get the error that it can't find the specified sound file "audiodeath:audiodeath.death".

I've confirmed that the audiodeath mod is working fine and is able to find its sound file correctly, and I've confirmed that Ding works fine in its default configuration. So I suspect it's to do with my configuration of Ding. Below are the parts of the file that I've modified.

ding {
    # Minecraft name of sound file to play when Minecraft is loaded
    # EG: "ui.button.click" or "entity.experience_orb.pickup"
    # 
    # This can also be a mod sound if the mod is installed.
    # EG: modname:modsound.boing [default: entity.experience_orb.pickup]
    S:name=**audiodeath:audiodeath.death**
    # Minecraft name of sound file to play when world is loaded
    # EG: "ui.button.click" or "entity.experience_orb.pickup"
    # 
    # This can also be a mod sound if the mod is installed.
    # EG: modname:modsound.boing [default: entity.experience_orb.pickup]
    S:nameWorld=**audiodeath:audiodeath.death**
    --LINES REMOVED
    # Play sound on...
    # 0 = Nothing (why install the mod though?)
    # 1 = MC load
    # 2 = World load
    # 3 = MC and World load [range: 0 ~ 3, default: 1]
    I:playOn=**3**

**Comment by iChun** [comment]
Does it work with any other mod sounds though? I'm pulling the sounds from the registry from the game, so unless audiodeath does something a little special, it should work fine.

Just spoke to Wyld and he tells me he got it working with audiodeath ages ago.

**Comment by iChun** [comment]
Also, the mod prints to the console if it can't find the sound you're looking for. Try check the console.
