### ISSUE TITLE
Resource pack sound not working

### ISSUE THREAD

**Issue by Maxwelljones** [iChun/Ding#10]
Hey there,
Thanks for such a great mod.

seems it doesn't accept sounds that aren't minecraft, even when added through resourcepack.
MC: 1.15.2
forge-31.2.36
error:

```
me.ichun.mods.ding.common.Ding
Render thread
Could not find sound: minecraft:nameofthesound
```

Anyone got it to work? How?

**Comment by iChun** [comment]
Could you try this out in 1.2.0, turn on the skipSoundEventCheck config

**Comment by Maxwelljones** [comment]
@iChun you are my hero ;)
Updating to 1.2.0 and SkipSoundEventCheck turned on works like a charm! 
Thank you for fixing it.
