### ISSUE TITLE
[1.15] Suggestion - Play the "ding" sound as music

### ISSUE THREAD

**Issue by Maxwelljones** [iChun/Ding#11]
Would be great to be able to "tag" the sound as music for example.

I know I dont use it as intended, but in my case I use it to start a specific music on server entry.
I got some complains that the music that started can't be lowered using the usual "music volume" options.

Version: MC 1.15

Thanks iChun ;) - even if you reply you can't or don't want to :P

**Comment by iChun** [comment]
Added configs for this in 1.16.x, a bit late but better late than never?

**Comment by Maxwelljones** [comment]
Yeah! Very cool! Thank you so much :)
