### ISSUE TITLE
Clientside only mod (1.16.5-1.3.0)

### ISSUE THREAD

**Issue by BideoGemu** [iChun/Ding#18]
Hi, can you update your mod to mark it as client only please. 
It will cause an error when we forget to install it on server and it's not easy for us, server admin, when we have lot of mod to manage.

You can find informations on:
https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods

Thanks

**Comment by iChun** [comment]
Ah. There's a mods.toml entry that I was missing. I've been wondering that
as I've done the extension point bit.

Thanks for this!

**Comment by iChun** [comment]
Done for the update to 1.19.3. Thanks again for this!
