### ISSUE TITLE
[1.19] Crashes with newest forge

### ISSUE THREAD

**Issue by Peca21** [iChun/Ding#19]
![Java-runtime-gamma Screenshot 2022 07 12 - 20 29 40 89](https://user-images.githubusercontent.com/13818400/178568067-a41f9f91-b121-42fd-bf65-49ca8abc9b1e.png)

Ding-1.19-1.3.0
forge-41.0-96
Log: https://paste.ee/p/yVwnU

**Comment by Baggytrousers27** [comment]
Issue comes from forge 41.0.94 onwards.

**Comment by ProsperCraft** [comment]
Same - https://gist.githubusercontent.com/ProsperCraft/d5fe54d651d3a8336859da4634fe01fc/raw/e09b15fc2b906dd09b2903ba581e88ff4ff03a89/gistfile1.txt

**Comment by mimi-min** [comment]
Same here... would love this as I do a lot of testing mods which means I need to reload a lot... 
I want to recommend it to my friends, too!

https://pastebin.com/Ghy5XCEx

**Comment by iChun** [comment]
Was fixed a while back! Closing!
