### ISSUE TITLE
asking

### ISSUE THREAD

**Issue by verixyt3** [iChun/Ding#31]
Hello, I'm asking you to make a version for _1.20.2 fabric or quilt on Modrinth_, **thank you very much!**

**Comment by iChun** [comment]
If you prop the project a follow you will get notified when it updates. Sorry to say, but asking if it will get updated will not get it updated any quicker, and this mod is open sourced which allows for other people to attempt at getting an update/port out as well should they need it badly enough.

That said, I have some time so I might be able to get this updated in within the coming days.

**Comment by iChun** [comment]
Ding has been updated on CurseForge and Modrinth
