### ISSUE TITLE
How to load a custom sound

### ISSUE THREAD

**Issue by micmou** [iChun/Ding#32]
So im using Kubejs to load a custom sound but I cant seem to make the mod load and play it ive tried a number of things and no matter what I do it refuses to play. The folder structure where it is at is kubejs/assets/kubejs/sounds/load.ogg 

Apparently github does not support uploading of ogg files so if you need the file let me know and ill gdrive it.

**Comment by iChun** [comment]
Which version of Ding?

**Comment by micmou** [comment]
1.4.1

**Comment by iChun** [comment]
MC version and loader?

**Comment by iChun** [comment]
Also can I just have a look at your config file for ding

**Comment by micmou** [comment]
Ohh sorry went to dinner

1.20.1
neoforge 47.1.79

and a config coming right up
Apparently neither does github support toml so here it is on pastebin
https://pastebin.com/WWNzhcwb

I tried a number of things in the config it is currently as shipped but ive tried pretty much every permutation I could think of.
In case you need it here is the sound im trying to load
https://drive.google.com/file/d/1OvuwLLCVnu5XPYBPPjWQeL0YhMBVlZ2B/view?usp=sharing

**Comment by iChun** [comment]
your config file shows the sound files are still set to default value which is "entity.experience_orb.pickup"

**Comment by micmou** [comment]
Ohh I thought I had typed that I had reset it to default ill list some of the values ive tried.
kubejs:load
kubejs:modsound.load
kubejs:kubejs.load
kubejs:sounds.load

**Comment by iChun** [comment]
can you share your mc log file? maybe latest.log or debug.log, are you sure kubejs has loaded the sound file properly? does the sound work when you use the /playsound command?

**Comment by micmou** [comment]
It does not appear that I can load the sound with playsound I assume that im incorrect in the assumption that kubejs would load it if I put it in the proper folder

**Comment by micmou** [comment]
Maybe I need a sounds.json well time to look up how to do that

**Comment by micmou** [comment]
Yay its working now
