### ISSUE TITLE
Ding after /reload command finishes

### ISSUE THREAD

**Issue by lonevox** [iChun/Ding#33]
This would be a lifesaver while developing my modpack. Running `/reload` takes around a minute and I don't have the time to stare at Minecraft until it finishes.

**Comment by iChun** [comment]
A couple months late to get to this, apologies.

I've had a quick look into this and the large issue is with how `/reload` is primarily a server-sided command. The server reloads all the data packs and then updates what it needs to the client once it's done. I'm not entirely sure when or where would be the best spot to hook in, and even then, I'm not sure it's the best idea to do so, especially when `/reload` isn't likely a command that people execute often unless like in your case, a mod pack.
