### ISSUE TITLE
[1.21][Neoforge] Neoforge 21.0.82 changes crash on launch

### ISSUE THREAD

**Issue by ffuentesm** [iChun/Ding#34]
https://pastebin.com/Krbji737
Ding-1.21-NeoForge-1.5.0
![image](https://github.com/user-attachments/assets/d045be9c-1360-4b5e-b243-ffa701f7bd4a)

**Comment by NielsPilgaard** [comment]
The same appears to happen for iChunUtil,
here's my latest.log in case it helps: https://gist.github.com/NielsPilgaard/3d26004754b74848b52075dfdaf77e65

**Comment by Periam** [comment]
Came to report the same issue with all the mods.
[debug.log](https://github.com/user-attachments/files/16235254/debug.log)
[latest.log](https://github.com/user-attachments/files/16235255/latest.log)

![Screenshot 2024-07-15 101252](https://github.com/user-attachments/assets/524fe2a0-ce30-42c2-828e-0a15458d528b)

**Comment by iChun** [comment]
Was fixed in iChunUtil 1.0.1
