### ISSUE TITLE
Not working with resource loader?

### ISSUE THREAD

**Issue by ghost** [iChun/Ding#4]
Hello! I am trying to make a custom work with resource loader on 1.12. My structure is like this: resources/minecraft/sounds/testing.ogg
The sounds.json looks like this: 
------------------------------------------
{
	"testing":{
		"category":"master",
		"sounds":[
			"testing"
		]
	}
}
----------------------------------------
When I type in Minecraft: "/playsound minecraft:testing voice jackowski" it plays the sound. But Ding doesn't play it. Also tried to add this sound to a resource pack, same issue.

**Comment by iChun** [comment]
What resource loader are you using?

**Comment by ghost** [comment]
Resource loader by Lumien

**Comment by iChun** [comment]
Are you still having issues with this currently?

**Comment by ghost** [comment]
Yes, latest version of both mods. When I type in the command "playsound minecraft:testing ambient jackowski" minecraft plays the sound correctly.
That's what ding says in the logs:
[Client thread/WARN] [ding]: Could not find sound: %s

**Comment by ghost** [comment]
I assume that resourceloader loading is quite different from resourcepacks, it does not work with the liteloader mods matmos and footstep presence and also does not work with optifine random textures.

**Comment by iChun** [comment]
Have you tried looking into using this mod? https://www.curseforge.com/minecraft/mc-mods/additional-resources From what I've been told, Audio Death uses this and Ding can play Audio Death's sound files.

**Comment by ghost** [comment]
I'll try it but for some reason audio death stopped working on my large modpack. Gonne dig around, thanks for the tip

**Comment by Vivigar** [comment]
Was this problem ever solved? I am having the same problem.

**Comment by ghost** [comment]
No, I used a other mod that let you add sounds on events

**Comment by Vivigar** [comment]
Which mod was it?


>

**Comment by ghost** [comment]
Sound Events. I used the "player logged on" trigger. I think they say it triggers only on multiplayer but iirc exactly the opposite happens

**Comment by Jordankcarney** [comment]
Ah, am still looking to have it play on game startup. What I did for now
was replace ui.toast.in sound since the sound fits for those too.

**Comment by Vivigar** [comment]
I still am not able to get this to work on 1.12.2 with either ResourceLoader or Additional Resources.
Maybe I am not putting my files in the right place?

Using Additional Resources:

![image](https://github.com/iChun/Ding/assets/47837025/4cbd6a7e-686f-4e88-827a-833757003ae7)

sounds.json:
`{
    "ambient.wow": {
        "category": "ambient",
        "sounds": [
            {
                "name": "wow"
            }
        ]
    }
}
`

Ding! cfg: 
`S:name=minecraft:ambient.wow`

It is setup the same way as needed for ResourceLoader. Both sounds can be used in-game using `/playsound minecraft:ambiant.wow ambient <playername>`

**Comment by yeemvrother** [comment]
Any solution to this? It will only play the ding sound, it doesn't seem to play any other sound, be it vanilla, custom(in a resource pack), or from another mod. I really wanted this for my modpack since no other mod offers this on 1.12.2. Does anyone have a fix??
