### ISSUE TITLE
Just doesn't work with AdditionalResources or ResourceLoader.

### ISSUE THREAD

**Issue by Vivigar** [iChun/Ding#6]
In the config it claims to work with sounds added by AdditionalResources and ResourceLoader, but it just doesn't. 

I can play the sound in-game with /playsound but Ding just can't find it.

It will log `[ding]: Could not find sound: minecraft:barry.wow` every single time without fail.

**Comment by iChun** [comment]
Could you try this out in 1.2.0, turn on the skipSoundEventCheck config
