### ISSUE TITLE
Mark mod as clientside only

### ISSUE THREAD

**Issue by phit** [iChun/Ding#7]
Please mark the mod as client only via
https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods

right now it will cause a red X in the server list if the mod is missing on the server, thanks!

**Comment by iChun** [comment]
Which version is this? I added the line for 1.16+ in June

**Comment by phit** [comment]
sorry, the 1.15 version, the change is on Github but never saw a release on CF

**Comment by iChun** [comment]
1.2.0 out now and backported to 1.15.2 as well. Enjoy!

**Comment by phit** [comment]
thanks!

**Comment by TheDeviantCrafter** [comment]
This is still an issue in Ding-1.6.1-1.2.0. Can this be re-opened?

**Comment by ArrowSamuel** [comment]
Mod still causes crashes on Server and removing it shows the red X on the server list.

It seems to still load on servers and looks for a sound class which isn't loaded on servers.
'Caused by: net.minecraftforge.fml.ModLoadingException: Ding has class loading errors'

**Comment by ghost** [comment]
Also requesting it be re-opened.
